INSERT INTO Local(id, nombre, email, password, CUIT, f_registro) VALUES(null, 'Viva la birra', 'domineyanina@hotmail.com', 'Prueba1', 123456789, '2025-01-01');

INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1001', 'Capital Federal', 'CABA - Retiro');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1002', 'Capital Federal', 'CABA - Monserrat');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1003', 'Capital Federal', 'CABA - San Nicolas');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1004', 'Capital Federal', 'CABA - San Nicolas');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1005', 'Capital Federal', 'CABA - San Nicolas');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1006', 'Capital Federal', 'CABA - Retiro');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1007', 'Capital Federal', 'CABA - Retiro');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1008', 'Capital Federal', 'CABA - Monserrat');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1009', 'Capital Federal', 'CABA - San Nicolas');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1010', 'Capital Federal', 'CABA - San Nicolas');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1011', 'Capital Federal', 'CABA - Retiro');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1012', 'Capital Federal', 'CABA - Monserrat');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1013', 'Capital Federal', 'CABA - San Nicolas');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1014', 'Capital Federal', 'CABA - Recoleta');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1015', 'Capital Federal', 'CABA - San Nicolas');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1016', 'Capital Federal', 'CABA - Recoleta');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1017', 'Capital Federal', 'CABA - San Nicolas');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1018', 'Capital Federal', 'CABA - Recoleta');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1019', 'Capital Federal', 'CABA - Recoleta');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1020', 'Capital Federal', 'CABA - Recoleta');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1021', 'Capital Federal', 'CABA - Recoleta');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1022', 'Capital Federal', 'CABA - Recoleta');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1023', 'Capital Federal', 'CABA - Balvanera');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1024', 'Capital Federal', 'CABA - Balvanera');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1025', 'Capital Federal', 'CABA - Recoleta');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1026', 'Capital Federal', 'CABA - Balvanera');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1027', 'Capital Federal', 'CABA - Balvanera');
INSERT INTO CodigoPostal(id, codigoPostal, provincia, localidad) VALUES (DEFAULT, '1028', 'Capital Federal', 'CABA - Balvanera');